CREATE TABLE MPM_DECISOES_HML (
	NATUREZA						VARCHAR2(100),
	CNJ								VARCHAR2(100),
	NUM_ANT							VARCHAR2(100),
	OJ								NUMBER,
	MAGISTRADO						NUMBER,
	DATA_DECISAO					DATE,
	CLASSE							NUMBER,
	FASE							NUMBER,
	COMPL1							NUMBER,
	COMPL2							NUMBER,
	COMPL3							NUMBER,
	ANO								NUMBER,
	MES								NUMBER
)