ALTER TABLE MPM_SUSPENSOS_ANALITICO
ADD COD_MAG NUMBER; -- Adjust the data type and size as needed

ALTER TABLE MPM_SUSPENSOS_ANALITICO
ADD COD_ORG_JULG NUMBER; -- Adjust the data type and size as needed

UPDATE MPM_SUSPENSOS_ANALITICO SA
SET 
    SA.COD_MAG = (SELECT M.CODMAG
                  FROM EJUD_DIM_MAGISTRADO M
                  WHERE SA.RELATOR = UPPER(M.NOME)),
    SA.COD_ORG_JULG = (SELECT OJ.CODORGJULG
                       FROM EJUD_DIM_ORGAO OJ
                       WHERE SA.ORGAO_JULGADOR = UPPER(OJ.NOME))
WHERE 
    EXISTS (SELECT 1 
            FROM EJUD_DIM_MAGISTRADO M, EJUD_DIM_ORGAO OJ
            WHERE SA.RELATOR = UPPER(M.NOME)
              AND SA.ORGAO_JULGADOR = UPPER(OJ.NOME));      
             
ALTER TABLE MPM_PENDENTES_ANALITICO
ADD COD_MAG NUMBER; -- Adjust the data type and size as needed

ALTER TABLE MPM_PENDENTES_ANALITICO
ADD COD_ORG_JULG NUMBER; -- Adjust the data type and size as needed
             
UPDATE MPM_PENDENTES_ANALITICO SA
SET 
    SA.COD_MAG = (SELECT M.CODMAG
                  FROM EJUD_DIM_MAGISTRADO M
                  WHERE SA.RELATOR = UPPER(M.NOME)),
    SA.COD_ORG_JULG = (SELECT OJ.CODORGJULG
                       FROM EJUD_DIM_ORGAO OJ
                       WHERE SA.ORGAO_JULGADOR = UPPER(OJ.NOME))
WHERE 
    EXISTS (SELECT 1 
            FROM EJUD_DIM_MAGISTRADO M, EJUD_DIM_ORGAO OJ
            WHERE SA.RELATOR = UPPER(M.NOME)
              AND SA.ORGAO_JULGADOR = UPPER(OJ.NOME));

SELECT * FROM  MPM_PENDENTES_ANALITICO;