SELECT ano,mes,count(1) FROM MPM_CASOSNOVOS_ANALITICO WHERE PRIMEIRA_FASE = 'S' GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_BAIXADOS_ANALITICO GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_DECISOES_ANALITICO GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_SUSPENSOS_ANALITICO GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_PENDENTES_ANALITICO GROUP BY ano,mes ORDER BY ano DESC, mes DESC;

SELECT * FROM MPM_CASOSNOVOS_ANALITICO where PRIMEIRA_FASE = 'S' ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_BAIXADOS_ANALITICO ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_DECISOES_ANALITICO ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_SUSPENSOS_ANALITICO ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_PENDENTES_ANALITICO ORDER BY ano DESC, mes DESC;

SELECT ano,mes,count(1) FROM MPM_CASOSNOVOS_HML WHERE PRIMEIRA_FASE = 'S' GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_BAIXADOS_HML GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_DECISOES_HML GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_SUSPENSOS_HML GROUP BY ano,mes ORDER BY ano DESC, mes DESC;
SELECT ano,mes,count(1) FROM MPM_PENDENTES_HML GROUP BY ano,mes ORDER BY ano DESC, mes DESC;

SELECT * FROM MPM_CASOSNOVOS_HML WHERE PRIMEIRA_FASE = 'S' ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_BAIXADOS_HML ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_DECISOES_HML ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_SUSPENSOS_HML ORDER BY ano DESC, mes DESC;
SELECT * FROM MPM_PENDENTES_HML ORDER BY ano DESC, mes DESC;

SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'DISTRIBUICAO' AND extract(YEAR FROM dthrmov) = 2024 AND extract(MONTH FROM dthrmov) = 12;
SELECT * FROM ejud.movimento@tj01 WHERE extract(YEAR FROM dthrmov) = 2024 AND extract(MONTH FROM dthrmov) = 12 AND codfase IN (26,36);

SELECT max(dthrmov) FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'DISTRIBUICAO';
SELECT max(dthrmov) FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'BAIXA';
SELECT max(dthrmov) FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'DECISAO';
SELECT max(dthrmov) FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'SUSPENSAO';
SELECT max(dthrmov) FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'SAIDA_SUSPENSAO';

SELECT * FROM EJUD_MPM_BASEDEDADOS ORDER BY dthrmov desc;
SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'DISTRIBUICAO' ORDER BY dthrmov desc;
SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'BAIXA' ORDER BY dthrmov desc;
SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'DECISAO' ORDER BY dthrmov desc;
SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'SUSPENSAO' ORDER BY dthrmov desc;
SELECT * FROM EJUD_MPM_BASEDEDADOS WHERE tipomov = 'SAIDA_SUSPENSAO' ORDER BY dthrmov desc;

SELECT 
    COALESCE(ph.ano, pa.ano) AS ano,
    COALESCE(ph.mes, pa.mes) AS mes,
    COALESCE(ph.count_pendentes_hml, 0) AS count_pendentes_hml,
    COALESCE(pa.count_pendentes_analitico, 0) AS count_pendentes_analitico,
    COALESCE(ph.count_pendentes_hml, 0) - COALESCE(pa.count_pendentes_analitico, 0) AS dif
FROM 
    (SELECT ano, mes, COUNT(1) AS count_pendentes_hml
     FROM MPM_PENDENTES_HML 
     GROUP BY ano, mes) ph
FULL OUTER JOIN 
    (SELECT ano, mes, COUNT(1) AS count_pendentes_analitico
     FROM MPM_PENDENTES_ANALITICO 
     GROUP BY ano, mes) pa
ON ph.ano = pa.ano AND ph.mes = pa.mes
ORDER BY ano DESC, mes DESC;

