SELECT DISTINCT TIPO FROM ejud.EstatCNBaixaPend@tj01;

SELECT * FROM ejud.EstatCNBaixaPend@tj01 WHERE TIPO = 'BAIXA';

SELECT 
    *
FROM ejud.EstatCNBaixaPend@tj01 
WHERE TIPO = 'BAIXA'
AND EXTRACT(YEAR FROM datafim) = 2024;

SELECT 
    tipo, dataini, datafim, qtdeProcesso, qtdeProcessoNCrim, qtdeelets, qtde1grau
FROM ejud.EstatCNBaixaPend@tj01 
WHERE TIPO = 'BAIXA'
AND EXTRACT(YEAR FROM datafim) = 2024;

------------------------
-- 	  BAIXADOS MPS    --
------------------------

SELECT * FROM DW_DEIGE.MPM_SUSPENSOS_SINTETICO;


DROP TABLE MPM_BAIXADOS_092024;
SELECT * FROM MPM_BAIXADOS_092024;

SELECT * FROM DGW_DISTRIBUI_BAIXA;

CREATE TABLE MPM_BAIXADOS_092024 as(
SELECT 
	P.NUM_PROCESSO, 
	P.CODDOC, 
	mov.codfase, 
	psa.dthrultmov AS dthr_ult_mov, 
	psa.CodUltLocal AS cod_ult_local, 
	psa.codultorgjulg AS cod_ult_org_julg, 
	psa.codultrel AS cod_ult_mag, 
	P.COD_COMPETENCIA, 
	TP.CODTIPPROC, 
	2024 AS ANO, 
	9 AS MES
FROM DGW_DISTRIBUI_BAIXA b
JOIN ejud.processosituacaoatual@tj01 psa ON b.coddoc = psa.coddoc
JOIN EJUD_FAC_PROCESSO p ON psa.coddoc = p.coddoc
JOIN ejud_dim_competencia c ON p.COD_COMPETENCIA = c.codcompt
JOIN ejud_dim_tipo tp ON p.COD_TIPO_PROCESSO = tp.codtipproc
JOIN ejud_fac_ult_movimento mov ON (mov.coddoc = psa.coddoc AND mov.dthrmov = psa.dthrultmov)
WHERE b.distrib IS NOT NULL
	and	EXTRACT(YEAR FROM b.baixa) = 2024
	AND EXTRACT(MONTH FROM b.baixa) = 9
	AND psa.CodUltLocal NOT IN (419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 583, 584, 1713, 1714, 1715, 1771, 2085, 5765)
	AND c.indconsrec = 'N'
	AND P.ID_PROCESSO_CORP IS NOT NULL
	AND P.COD_COMPETENCIA <> 9
	AND TP.CODTIPPROC NOT IN (5, 54, 30, 73, 40, 41, 42, 93, 94, 95, 297)
  );
  
SELECT * FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM baixa) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND DISTRIB IS NOT NULL;

------------------------------
-- 	 PROCURANDO DIFERENÇAS  --
------------------------------
 
SELECT * FROM MPM_BAIXADOS_ANALITICO;
SELECT * FROM MPM_BAIXADOS;

DROP TABLE MPM_BAIXADOS;

SELECT * FROM (
WITH ejud_extracao AS 
(
	SELECT 
		BA.ANO,
		BA.MES,
		BA.DATA_DA_BAIXA, 
		BA.RELATOR AS COD_MAG, 
		BA.ORGAO_JULGADOR AS COD_ORG_JULG, 
		BA.CLASSE_CNJ AS COD_CLASSE,
		TP.DESCR AS CLASSE,
		BA.CNJ AS NUM_PROCESSO
	FROM MPM_BAIXADOS_ANALITICO BA
	LEFT JOIN EJUD_DIM_TIPO TP ON BA.CLASSE_CNJ = TP.codext
	WHERE EXTRACT(YEAR FROM BA.DATA_DA_BAIXA) = 2024 
	AND EXTRACT(MONTH FROM BA.DATA_DA_BAIXA) = 9
), 
banco_extracao as 
(
	SELECT 
		B.ANO,
		B.MES,
		B.DATA_DA_BAIXA, 
		B.COD_ULT_MAG AS COD_MAG, 
		B.COD_ULT_ORG_JULG, 
		B.CODTIPPROC AS COD_CLASSE,
		TP.DESCR AS CLASSE,
		B.NUM_PROCESSO
	FROM MPM_BAIXADOS B
	JOIN EJUD_DIM_TIPO TP ON TP.CODTIPPROC = B.CODTIPPROC
	WHERE EXTRACT(YEAR FROM B.DATA_DA_BAIXA) = 2024 
	AND EXTRACT(MONTH FROM B.DATA_DA_BAIXA) = 9 
)
SELECT 
    COALESCE(ejud_extracao.NUM_PROCESSO, banco_extracao.NUM_PROCESSO) AS NUM_PROCESSO,
    ejud_extracao.COD_MAG AS COD_MAG_EJUD,
    banco_extracao.COD_MAG AS COD_MAG_EXTRACAO,
    ejud_extracao.DATA_DA_BAIXA AS DATA_DA_BAIXA_EJUD,
    banco_extracao.DATA_DA_BAIXA AS DATA_DA_BAIXA_EXTRACAO,
    ejud_extracao.COD_CLASSE AS COD_CLASSE_EJUD,
    banco_extracao.COD_CLASSE AS COD_CLASSE_EXTRACAO,
    ejud_extracao.CLASSE AS CLASSE_EJUD,
    banco_extracao.CLASSE AS CLASSE_EXTRACAO,
    CASE 
        WHEN ejud_extracao.NUM_PROCESSO IS NOT NULL AND banco_extracao.NUM_PROCESSO IS NOT NULL THEN 'AMBOS'
        WHEN ejud_extracao.NUM_PROCESSO IS NOT NULL THEN 'SISTEMA_EJUD'
        WHEN banco_extracao.NUM_PROCESSO IS NOT NULL THEN 'EXTRACAO_MPS'
    END AS FLAG
FROM ejud_extracao
FULL OUTER JOIN banco_extracao
ON ejud_extracao.NUM_PROCESSO = banco_extracao.NUM_PROCESSO
) WHERE FLAG IN ('AMBOS','SISTEMA_EJUD', 'EXTRACAO_MPS');

------------------------------
-- 	 PROCURANDO BAIXADOS    --
------------------------------

SELECT * FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND DISTRIB IS NULL AND BAIXA IS NULL AND ROWNUM <= 5; --FALSO
SELECT * FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND DISTRIB IS NULL AND BAIXA IS NOT NULL AND ROWNUM <= 5; --VERDADEIRO
SELECT * FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND DISTRIB IS NOT NULL AND BAIXA IS NULL AND ROWNUM <= 5; --FALSO
SELECT * FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND DISTRIB IS NOT NULL AND BAIXA IS NOT NULL AND ROWNUM <= 5; --VERDADEIRO

SELECT COUNT(1) FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND ((DISTRIB IS NOT NULL AND BAIXA IS NOT NULL) OR (DISTRIB IS NOT NULL AND BAIXA IS NOT NULL)); --VERDADEIRO
SELECT COUNT(1) FROM DGW_DISTRIBUI_BAIXA WHERE EXTRACT(YEAR FROM BAIXA) = 2024 AND EXTRACT(MONTH FROM BAIXA) = 9 AND BAIXA IS NOT null;

SELECT MOV.*,F.DESCR 
FROM EJUD_FAC_ULT_MOVIMENTO MOV 
JOIN EJUD_DIM_FASE F ON MOV.CODFASE = F.CODFASE
WHERE MOV.CODDOC IN (27669824,27644077,27529401,27464098,27701514)
AND MOV.CODFASE IN (22,60,123,861,870,50002,50011,50014)
ORDER BY MOV.CODDOC,MOV.DTHRMOV;

SELECT MOV.*,F.DESCR 
FROM baixados_092024 MOV 
JOIN EJUD_DIM_FASE F ON MOV.CODFASE = F.CODFASE
WHERE CODDOC IN (27351718,27349672,26941710,27467485,25507275)
AND MOV.CODFASE IN (22,60,123,861,870,50002,50011,50014)
ORDER BY MOV.CODDOC,MOV.DTHRMOV;

SELECT * FROM EJUD_DIM_FASE;

------------------------------
-- 	 DEFININDO BAIXADOS     --
------------------------------

BEGIN 
	P_POPULADGW_DISTRIBUI_BAIXA_4;
END;

SELECT *
FROM USER_ERRORS 
WHERE name = 'P_POPULADGW_DISTRIBUI_BAIXA_4' AND type = 'PROCEDURE';



