CREATE TABLE mpm_log_execucao (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR2(100),
    data_execucao TIMESTAMP
);

INSERT INTO mpm_log_execucao (nome, data_execucao)
    VALUES ('your_procedure', SYSTIMESTAMP);